### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by Rafacolacio** [ICEI-PUC-Minas-PMV-ADS/PetShower#8]
[Untitled.pdf](https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t10-pmv-ads-2023-2-e2-projetopet/files/12706688/Untitled.pdf)

**Comment by danicarvalhomf** [comment]
Influir as imagens diretamente na página: https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t10-pmv-ads-2023-2-e2-projetopet/blob/main/docs/04-Projeto%20de%20Interface.md
